Move S3 inits

diff --git a/scripts/_init b/scripts/_init
--- a/scripts/_init
+++ b/scripts/_init
@@ -65,11 +65,52 @@ DEFAULT_S3_HOST=$(node -p "require('$ROOT_DIR/package.json')['cli-engine'].s3.ho
 S3_HOST="${S3_HOST:-"$DEFAULT_S3_HOST"}"
 S3_HOST_SCHEME="${S3_HOST_SCHEME:-"https"}"
 S3_HOST_BASE_URL="$S3_HOST_SCHEME://$S3_HOST/$S3_CHANNEL_SUBFOLDER"
-
+S3_PROFILE_NAME="sfdx"
 
 function len() {
     echo ${#1}
 }
+
+function awsConfigureSetFromEnvVar() {
+    if [ $# -ne 3 ]; then
+        echo "assertion expected 3 arguments but received $#"
+        exit 1
+    fi
+
+    if [ -z ${1} ] || [[ $(len "${!1}") -eq 0 ]]; then
+        echo "Missing Env Variable for $1"
+        exit 1
+    fi
+
+    aws configure set $2 ${!1} --profile $3
+}
+
+if [[ -z "${S3_ENDPOINT:-}" ]]; then
+    echo "S3_ENDPOINT is not defined. Specify an S3 endpoint url or 'AWS'"
+    exit 1
+fi
+
+if [[ -z "${NPM_REGISTRY:-}" ]]; then
+    echo "NPM_REGISTRY is not defined. Specify and npm registry url"
+    exit 1
+fi
+
+set +e
+CURRENT_S3_REGION="$(aws configure get region --profile $S3_PROFILE_NAME)"
+set -e
+
+if [ $S3_ENDPOINT != "AWS" ]; then
+
+    S3_PROFILE="sfdx"
+
+    if [ "$CURRENT_S3_REGION" != "${S3_REGION}" ]; then
+
+        awsConfigureSetFromEnvVar "S3_REGION" "region" $S3_PROFILE_NAME
+        awsConfigureSetFromEnvVar "S3_ACCESS_KEY" "aws_access_key_id" $S3_PROFILE_NAME
+        awsConfigureSetFromEnvVar "S3_SECRET" "aws_secret_access_key" $S3_PROFILE_NAME
+        aws configure list $S3_PROFILE
+    fi
+fi
 
 # S3 cache-control maxage constants
 if [[ "$CHANNEL" == "stable" ]]; then
