ci: github actions for rc creation

diff --git a/.github/workflows/dockerBuildFull.yml b/.github/workflows/dockerBuildFull.yml
--- a/.github/workflows/dockerBuildFull.yml
+++ b/.github/workflows/dockerBuildFull.yml
@@ -1,11 +1,5 @@
 name: docker-full
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        description: version to build from tarball, ex 7.155.0
-        type: string
-        required: true
   workflow_call:
     inputs:
       version:
@@ -13,14 +7,9 @@ on:
         required: true
 
 jobs:
-  buildTestPush:
+  buildPush:
     runs-on: ubuntu-latest
     steps:
-      # Limitation: versions file will contain the last 20 releases
-      - id: versionCurl
-        name: Get url for version
-        run: echo "::set-output name=url curl 'https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json' | jq '.[\"${{ inputs.version }}\"]'"
-
       - name: Check out the repo
         uses: actions/checkout@v3
 
@@ -36,22 +25,34 @@ jobs:
         with:
           images: salesforce/salesforcedx
 
-      - name: Build for verification
-        uses: docker/build-push-action@v3
+      - name: Build and push Docker image
+        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
         with:
           context: .
-          load: true
-          tags: salesforce/salesforcedx:${{ inputs.version }}-full
+          push: true
+          labels: ${{ steps.meta.outputs.labels }}
+          file: dockerfiles/Dockerfile_full
           build-args: |
             SALESFORCE_CLI_VERSION=${{ inputs.version}}
             SF_CLI_VERSION=latest-rc
-          file: dockerfiles/Dockerfile_full
-      - name: Verify full dependencies
+          tags: salesforce/salesforcedx:latest-rc-full, salesforce/salesforcedx:${{ inputs.version }}-full
+
+  verify:
+    needs: buildPush
+    runs-on: ubuntu-latest
+    container:
+      image: salesforce/salesforcedx:${{ inputs.version }}-full
+    steps:
+      - name: verify node, sfdx, jq
+        # without bash this will fail.  Not sure what the default shell is but it doesn't like the [[(())]] bashism
+        shell: bash
         run: |
-          TAG=echo "salesforce/salesforcedx:${{ inputs.version }}-full"
-          NODE_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'node -v')"
-          SFDX_CLI_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'sfdx --version')"
-          JQ_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'jq --version')"
+          set -e
+          node -v
+          sfdx version --verbose
+          jq --help
+          NODE_VERSION=$(sfdx version --verbose --json | jq '.nodeVersion')
+          SFDX_CLI_VERSION=$(sfdx version --verbose --json | jq '.cliVersion')
           if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
           then
             echo "sfdx-cli installed -" $SFDX_CLI_VERSION
@@ -66,21 +67,3 @@ jobs:
             echo "The node installation could not be verified"
             exit 1
           fi
-          if [[ ((`echo $JQ_VERSION | grep -c "jq"` > 0))]]
-          then
-            echo "jq installed -" $JQ_VERSION
-          else
-            echo "The jq installation could not be verified"
-            exit 1
-          fi
-      - name: Build and push Docker image
-        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
-        with:
-          context: .
-          push: true
-          labels: ${{ steps.meta.outputs.labels }}
-          file: dockerfiles/Dockerfile_full
-          build-args: |
-            SALESFORCE_CLI_VERSION=${{ inputs.version}}
-            SF_CLI_VERSION=latest-rc
-          tags: salesforce/salesforcedx:latest-rc-full, salesforce/salesforcedx:${{ inputs.version }}-full
diff --git a/.github/workflows/dockerBuildSlim.yml b/.github/workflows/dockerBuildSlim.yml
--- a/.github/workflows/dockerBuildSlim.yml
+++ b/.github/workflows/dockerBuildSlim.yml
@@ -1,11 +1,5 @@
 name: docker-slim
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        type: string
-        required: true
-        description: version to build from tarball, ex 7.155.0
   workflow_call:
     inputs:
       version:
@@ -13,22 +7,34 @@ on:
         required: true
 
 jobs:
-  buildTestPush:
+  buildPush:
     runs-on: ubuntu-latest
     steps:
-      # Limitation: versions file will contain the last 20 releases and NOT rc until it's promoted
+      # Limitation: versions file will contain the last 20 releases and NOT rc until it's promoted to latest
       - id: versionCurl
         if: inputs.version != 'latest-rc'
         name: Get url for version
-        run: echo "::set-output name=url curl 'https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json' | jq '.[\"${{ inputs.version }}\"]'"
+        run: echo "::set-output name=url::$(curl -s 'https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json' | jq -r '.[\"${{ inputs.version }}\"]')"
 
       - id: rcCurl
         if: inputs.version == 'latest-rc'
         name: Get url for latest-rc
-        run: echo "::set-output name=url curl 'https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json' | jq '.xz'"
+        run: echo "::set-output name=url::$(curl -s 'https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-linux-x64-buildmanifest' | jq -r '.xz')"
+
+      - id: regex
+        uses: actions-ecosystem/action-regex-match@9e6c4fb3d5e898f505be7a1fb6e7b0a278f6665b
+        with:
+          text: ${{ steps.versionCurl.outputs.url || steps.rcCurl.outputs.url }}
+          regex: '(\d+\.\d+\.\d+)'
+          flags: g
+
+      - run: echo "regex found version ${{steps.regex.outputs.group1}}"
 
       - name: Check out the repo
         uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
       - name: Log in to Docker Hub
         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
@@ -42,21 +48,31 @@ jobs:
         with:
           images: salesforce/salesforcedx
 
-      - name: Build for verification
-        uses: docker/build-push-action@v3
+      - name: Build and push Docker image
+        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
         with:
           context: .
-          load: true
-          tags: salesforce/salesforcedx:${{ inputs.version }}-slim
+          push: true
+          labels: ${{ steps.meta.outputs.labels }}
           file: dockerfiles/Dockerfile_slim
           build-args: |
             DOWNLOAD_URL=${{ steps.versionCurl.outputs.url || steps.rcCurl.outputs.url }}
+          tags: salesforce/salesforcedx:latest-rc-slim, salesforce/salesforcedx:${{ steps.regex.outputs.group1 }}-slim
 
-      - name: Verify slim dependencies
+  verify:
+    needs: buildPush
+    runs-on: ubuntu-latest
+    container:
+      image: salesforce/salesforcedx:${{ inputs.version }}-slim
+    steps:
+      - name: verify sfdx, java
+        # without bash this will fail.  Not sure what the default shell is but it doesn't like the [[(())]] bashism
+        shell: bash
         run: |
-          TAG=echo "salesforce/salesforcedx:${{ inputs.version }}-slim"
-          SFDX_CLI_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'sfdx --version')"
-          JAVA_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'java --version | head -n 1')"
+          set -e
+          sfdx version
+          SFDX_CLI_VERSION=$(sfdx version)
+          JAVA_VERSION=$(java --version | head -n 1)
           if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
           then
             echo "sfdx-cli installed -" $SFDX_CLI_VERSION
@@ -71,14 +87,3 @@ jobs:
             echo "The Java installation could not be verified"
             exit 1
           fi
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
-        with:
-          context: .
-          push: true
-          labels: ${{ steps.meta.outputs.labels }}
-          file: dockerfiles/Dockerfile_slim
-          build-args: |
-            DOWNLOAD_URL=${{ steps.versionCurl.outputs.url }}
-          tags: salesforce/salesforcedx:latest-rc-slim, salesforce/salesforcedx:${{ inputs.version }}-slim
