ci: slim verify-only [skip ci]

diff --git a/.github/workflows/dockerBuildSlim.yml b/.github/workflows/dockerBuildSlim.yml
--- a/.github/workflows/dockerBuildSlim.yml
+++ b/.github/workflows/dockerBuildSlim.yml
@@ -14,53 +14,63 @@ on:
         required: true
 
 jobs:
-  buildTestPush:
+  # buildTestPush:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # Limitation: versions file will contain the last 20 releases and NOT rc until it's promoted
+  #     - id: versionCurl
+  #       if: inputs.version != 'latest-rc'
+  #       name: Get url for version
+  #       run: echo "::set-output name=url::$(curl -s 'https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json' | jq '.[\"${{ inputs.version }}\"]')"
+
+  #     - id: rcCurl
+  #       if: inputs.version == 'latest-rc'
+  #       name: Get url for latest-rc
+  #       run: echo "::set-output name=url::$(curl -s 'https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-linux-x64-buildmanifest' | jq '.xz')"
+
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v3
+
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
+
+  #     - name: Log in to Docker Hub
+  #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWORD }}
+
+  #     - name: Extract metadata (tags, labels) for Docker
+  #       id: meta
+  #       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
+  #       with:
+  #         images: salesforce/salesforcedx
+
+  #     - name: Build and push Docker image
+  #       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
+  #       with:
+  #         context: .
+  #         push: true
+  #         labels: ${{ steps.meta.outputs.labels }}
+  #         file: dockerfiles/Dockerfile_slim
+  #         build-args: |
+  #           DOWNLOAD_URL=${{ steps.versionCurl.outputs.url || steps.rcCurl.outputs.url }}
+  #         tags: salesforce/salesforcedx:latest-rc-slim, salesforce/salesforcedx:${{ inputs.version }}-slim
+
+  verify:
+    # needs: buildPush
     runs-on: ubuntu-latest
+    container:
+      image: salesforce/salesforcedx:${{ inputs.version }}-slim
     steps:
-      # Limitation: versions file will contain the last 20 releases and NOT rc until it's promoted
-      - id: versionCurl
-        if: inputs.version != 'latest-rc'
-        name: Get url for version
-        run: echo "::set-output name=url::$(curl -s 'https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json' | jq '.[\"${{ inputs.version }}\"]')"
-
-      - id: rcCurl
-        if: inputs.version == 'latest-rc'
-        name: Get url for latest-rc
-        run: echo "::set-output name=url::$(curl -s 'https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-linux-x64-buildmanifest' | jq '.xz')"
-
-      - name: Check out the repo
-        uses: actions/checkout@v3
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
-        with:
-          images: salesforce/salesforcedx
-
-      - name: Build for verification
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          load: true
-          tags: salesforce/salesforcedx:${{ inputs.version }}-slim
-          file: dockerfiles/Dockerfile_slim
-          build-args: |
-            DOWNLOAD_URL=${{ steps.versionCurl.outputs.url || steps.rcCurl.outputs.url }}
-
-      - name: Verify slim dependencies
+      - name: verify check node version
+        # without bash this will fail.  Not sure what the default shell is but it doesn't like the [[(())]] bashism
+        shell: bash
         run: |
-          TAG=echo "salesforce/salesforcedx:${{ inputs.version }}-slim"
-          SFDX_CLI_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'sfdx --version')"
-          JAVA_VERSION="$(docker run -it --rm salesforce/salesforcedx:$TAG bash -c 'java --version | head -n 1')"
+          set -e
+          sfdx version --verbose
+          SFDX_CLI_VERSION=$(sfdx version --verbose --json | jq '.cliVersion')
+          JAVA_VERSION=$('java --version | head -n 1')
           if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
           then
             echo "sfdx-cli installed -" $SFDX_CLI_VERSION
@@ -75,14 +85,3 @@ jobs:
             echo "The Java installation could not be verified"
             exit 1
           fi
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
-        with:
-          context: .
-          push: true
-          labels: ${{ steps.meta.outputs.labels }}
-          file: dockerfiles/Dockerfile_slim
-          build-args: |
-            DOWNLOAD_URL=${{ steps.versionCurl.outputs.url || steps.rcCurl.outputs.url }}
-          tags: salesforce/salesforcedx:latest-rc-slim, salesforce/salesforcedx:${{ inputs.version }}-slim
