chore: add promote-verify to nightly promote

diff --git a/.github/workflows/promote-nightly-to-rc.yml b/.github/workflows/promote-nightly-to-rc.yml
--- a/.github/workflows/promote-nightly-to-rc.yml
+++ b/.github/workflows/promote-nightly-to-rc.yml
@@ -18,8 +18,40 @@ jobs:
       old-channel: nightly
       new-channel: latest-rc
 
+  promote-verify:
+    runs-on: ubuntu-latest
+    needs: [promote]
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: lts/*
+          cache: yarn
+      - run: ./scripts/verify-promote nightly latest-rc
+      - run: npm install -g @salesforce/plugin-release-management --omit=dev
+      - run: |
+          ATTEMPT=1
+          MAX=5
+          DELAY=120 # two minutes
+
+          # Retry several times because the S3 cache can cause failures
+          # Command: sf-release cli:versions:inspect -c stable-rc -l archive
+
+          while true; do
+              sf-release cli:versions:inspect -c stable-rc -l archive && break || {
+                  if [[ $ATTEMPT -lt $MAX ]]; then
+                      ((ATTEMPT++))
+                      echo "Promote verify failed - trying again ($ATTEMPT/$MAX)"
+                      sleep $DELAY;
+                  else
+                      "Exiting after $ATTEMPT failed attempts"
+                      exit 1
+                  fi
+              }
+          done
+
   announce-promotion-to-slack:
-    needs: promote
+    needs: [promote-verify]
     runs-on: ubuntu-latest
     steps:
       - name: Get nightly version
